src/cavendish_particle_tracks/_stereoshift_dialog.py, tests/test_stereoshift_dialog.py
Adding one additional reference point to solve #53.
When testing found a bug in the depth calculation that was not caught by previous test. Enlarged test base to cover for this.
=> Adding one more reference point to fix stereoshift calculation + bug fix

.pre-commit-config.yaml, README.md, src/cavendish_particle_tracks/_decay_angles_dialog.py, src/cavendish_particle_tracks/_stereoshift_dialog.py
Resolved soon to be deprecated edge_color reference and replaced with the new border_color following warning from terminal output.
=> Resolved to-be-deprecated UI reference.

CONTRIBUTING.md, LICENSE.md, pyproject.toml
Also update a path and python versions in CONTIBUTING.md whilst I'm at it.
=> Add you to contributors!

.github/workflows/test_and_deploy.yml
=> Added windows tests

src/cavendish_particle_tracks/_widget.py
Added axis label to event selection.
=> Added axis label.

src/cavendish_particle_tracks/_magnification_dialog.py, src/cavendish_particle_tracks/_widget.py, tests/test_magnification_dialog.py
Magnification is not currently covered by tests.
=> Improving test coverage.

CONTRIBUTING.md, README.md, docs/index.rst, docs/user-manual.md, pyproject.toml
Add user manual to the `doc` pages.
=> User manual

src/cavendish_particle_tracks/_widget.py, tests/conftest.py, tests/test_save.py, tests/test_widget.py
Add a dialog to allow the user to choose the name and location of the output file.
The data is saved only as `.csv` for the moment, might want to consider other file types in the future.
=> Save as dialog

launch_debug.py, pyproject.toml
=> Remove explicit qtpy dependency

src/cavendish_particle_tracks/_magnification_dialog.py
Reverts palvarezc/cavendish-particle-tracks#124
=> Revert "Magnification refactoring changes"

.github/workflows/lint_and_test.yml
[Yeah this didn't work](https://github.com/palvarezc/cavendish-particle-tracks/actions/runs/10874410261/job/30171696684).
So let's turn it off for now.  Maybe later.
=> Don't actually want to try deploying to pypi.

src/cavendish_particle_tracks/__init__.py, src/cavendish_particle_tracks/_analysis.py, src/cavendish_particle_tracks/_decay_angles_dialog.py, src/cavendish_particle_tracks/_magnification_dialog.py, src/cavendish_particle_tracks/_main_widget.py, src/cavendish_particle_tracks/_stereoshift_dialog.py, src/cavendish_particle_tracks/_widget.py, src/cavendish_particle_tracks/napari.yaml, tests/conftest.py, tests/test_decay_angles_dialog.py, tests/test_magnification_dialog.py, tests/test_save.py, tests/test_stereoshift_dialog.py, tests/test_widget.py
Some tidying and light refactoring.
=> Tidy up names, expand tlas and abbvns, correct docstrings, and refactor the magnification dialog's constructor

src/cavendish_particle_tracks/_analysis.py, src/cavendish_particle_tracks/_main_widget.py
Propagate the change:
- `NewParticle.Name` -> `ParticleDecay.name` 
to the functions that populate the table in `_main_widget.py`
=> Fix broken table

src/cavendish_particle_tracks/_main_widget.py, tests/test_env.py
Introduce a new environment variable `CPT_SHUFFLING_SEED` to set the seed for the random shuffling of the images when loaded.
=> Control data shuffling with an environment variable

pyproject.toml, src/cavendish_particle_tracks/_calculate.py, src/cavendish_particle_tracks/_decay_angles_dialog.py, src/cavendish_particle_tracks/_magnification_dialog.py, src/cavendish_particle_tracks/_main_widget.py, src/cavendish_particle_tracks/_stereoshift_dialog.py, tests/test_decay_angles_dialog.py, tests/test_env.py, tests/test_magnification_dialog.py, tests/test_misc.py, tests/test_save.py, tests/test_stereoshift_dialog.py, tests/test_widget.py
`black` used to advocate for 88 characters.
[Raymond H says "90-ish"](https://youtu.be/wf-BqAjZb8M?feature=shared).
> _Try to stick to 90, but not at the expense of great variable names._
So I propose we relax to at least 90 for readability and to stop excessive wrapping.
_Edit_: we save about 100 linebreaks by doing this. So the code shrinks!
=> Relax line length

src/cavendish_particle_tracks/_decay_angles_dialog.py
Solves 
- #61.
I also gave the variables nicer names than `widget`.
=> Add titles to decay angles dialog table.

src/cavendish_particle_tracks/_decay_angles_dialog.py, src/cavendish_particle_tracks/_magnification_dialog.py, src/cavendish_particle_tracks/_main_widget.py, src/cavendish_particle_tracks/_settings.py, tests/test_decay_angles_dialog.py, tests/test_magnification_dialog.py, tests/test_widget.py
Solves
- #133 
which is nice from a maintainability point of view.
=> Neaten up constants and move getting settings from env out of the main widget.

src/cavendish_particle_tracks/_main_widget.py, src/cavendish_particle_tracks/analysis.py, tests/test_stereoshift_dialog.py, tests/test_widget.py
Test data corruption on radius measurement. Reproduces: 
- #171
=> Data corruption on radius and length measurements

src/cavendish_particle_tracks/_magnification_dialog.py, src/cavendish_particle_tracks/_stereoshift_dialog.py
With this the notifications to the user get more homogeneous throughout the different measurements.
Probably something to add before the second release.
=> Adding feedback to the user on calculation of magnification and stereoshift

launch_debug.py, src/cavendish_particle_tracks/_main_widget.py, src/cavendish_particle_tracks/_settings.py, tests/test_env.py, tests/test_widget.py
I did not make the bypass option any stronger than it already is. We could do that if you want, e.g. have all buttons enabled all the time.
=> Take the "bypass button disable" option from the environment.
