palvarezc/cavendish-particle-tracks

- launch_debug.py
launch_debug creates an instance of napari with the plugin loaded. Breakpoints can now be set to assist debugging.
> Added debug mode.

- pyproject.toml
- src/cavendish_particle_tracks/_stereoshift_dialog.py
The feature `Open Files as Stack` does not seem to work from napari 0.5.0 onwards. This feature is needed for the data loading (#48).
Here we revert to napari>=4.0.18, <0.5.0 and revert some of @Joseph-Garvey 's changes (https://github.com/palvarezc/cavendish-particle-tracks/pull/54) as they break in these versions.
> Reverting napari version to 0.4.18/19

- .github/workflows/test_and_deploy.yml
Now that the repo is open source, there's no reason not to run MacOS tests. You can also add Windows tests if you really must.
> Reenable tests on MacOS.

- tests/conftest.py
- tests/test_decay_angles_dialog.py
- tests/test_save.py
- tests/test_stereoshift_dialog.py
- tests/test_widget.py
We can have our own custom `pytest.fixture` to abstract out the common test function setup code. [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)s up the tests.
> Add pytest fixture to set up the `ParticleTracksWidget`.

- src/cavendish_particle_tracks/_stereoshift_dialog.py
Resolved bug created in PR #64.
Data request to layer was not updated to reflect that there are now 6 points instead of 5. self.spoints threw an error because it received 5 args instead of 4.
> Resolved bug created created in PR #64

- README.md
Solves 
- #84
Noting that we always said "follow napari installation instructions" but this makes it explicit. 
Also: I deliberately don't add explicit `conda create`... steps here because that's duplicating the napari instructions which is bad (users/lab computer IT people should install napari however napari says they should).
Not related to this PR, but 
* has anyone tried installing it on whatever you will have for lab computers?
* I understood we'd _not_ be supporting Windows, is this still the case? Because we're now [testing it in CI](https://github.com/palvarezc/cavendish-particle-tracks/blob/main/.github/workflows/test_and_deploy.yml#L45-L50).
> Specify installation instructions for macOS.

- tests/test_decay_angles_dialog.py
Doing as the `DeprecationWarning` very helpfully told me:
```
tests/test_decay_angles_dialog.py::test_decay_angles_dialog
/Users/runner/work/cavendish-particle-tracks/cavendish-particle-tracks/.tox/py311-macos/lib/python3.11/site-packages/pytestqt/qtbot.py:267: DeprecationWarning: waitForWindowShown is deprecated, as the underlying Qt method was obsoleted in Qt 5.0 and removed in Qt 6.0. Its name is imprecise and the pytest-qt wrapper does not raise qtbot.TimeoutError if the window wasn't shown. Please use the qtbot.waitExposed context manager instead.
```
> Use context manager as recommended in deprecation warning.

- src/cavendish_particle_tracks/_stereoshift_dialog.py
- tests/test_stereoshift_dialog.py
Bug fix for `Save to table` action in the `StereoshiftDialog`, when no particles have been added to the table.
Will become redundant when enable/disable buttons is implemented.
> Stereoshift dialog: save to table

- CONTRIBUTING.md
- README.md
- docs/api.rst
- docs/index.rst
- pyproject.toml
As most of the code is private ... `_private_module.py` or `Widget._private_member` it isn't documented by default anyway. And it's not really for the users to read. Can always revisit if it's useful later.
- GitHub link to the code.
- Update some project URLs.
- Found a few mentions of Python 3.8.
> Remove API docs from the website, add a GitHub logo link, and update some outdated things.

- src/cavendish_particle_tracks/_decay_angles_dialog.py
- src/cavendish_particle_tracks/_magnification_dialog.py
- src/cavendish_particle_tracks/_stereoshift_dialog.py
- src/cavendish_particle_tracks/_widget.py
- tests/test_decay_angles_dialog.py
- tests/test_magnification_dialog.py
- tests/test_stereoshift_dialog.py
Trying to separate out the different elements from:
- #104 
In this PR: 
- Avoid layer duplication when repeatedly hitting the same Magnification, Stereoshift or Decay angles button
- Tried to `cherry-pick` from @Joseph-Garvey commits
- Changed the implementation with `QApplication` to use some flags instead, as the tests open several `QApplication` instances and finding a widget from all applications was not safe.
> Avoid tool duplication

- pyproject.toml
- src/cavendish_particle_tracks/_widget.py
Provisional hack while we figure out how to dock at the bottom by default:
- Load button disabled when the data has been loaded
- Layer controls hiden from the user
> Load button disable + hide layer controls

- src/cavendish_particle_tracks/_widget.py
- tests/test_widget.py
On click of the close button for the widget or the main window, open a message box offering the option to save the data.
> Offer save data dialog on widget closure

- src/cavendish_particle_tracks/_main_widget.py
From #141 (user testing)
> Advise students to not click the "Change the order of visible axes" icon, it made my computer struggle a bit.
What's better than telling someone not to press the big red button?
remove the big red button.
The user doesn't need to use the other buttons in this toolbar anyways, so no harm in removing it.
This doesn't change the dependency on Napari <0.6.0, as this is required by the deletion of the layer menu anyways.
> Prevent crash due to view rotation.

- src/cavendish_particle_tracks/_decay_angles_dialog.py
Addressing user feedback:
- #141 
regarding the bug with the decay angles dialog, which will not reopen after it has been opened and closed once.
> Fix error with re-launching decay angles dialog

- src/cavendish_particle_tracks/_magnification_dialog.py
Addressing user feedback:
- #141 
regarding the extra click needed to select the "Radii and Lengths" layer after the magnification dialog is closed.
> After magnification dialog is closed, return focus to measurements layer

- tests/test_magnification_dialog.py
Add tests to check that the different dialogs are shown when they are called from the main widget.
> Test the dialogs are shown

- src/cavendish_particle_tracks/_analysis.py
- src/cavendish_particle_tracks/_main_widget.py
- tests/test_widget.py
The `Event` dimension of the data randomly reshuffled according to the new parameter `reshuffling_seed`. The idea is to set this seed differently for different machines.
Also, `napari` shows the centre of the stack by default. Changed behaviour to show first event on loading the data.
Added a check of the number of images per view, to avoid:
- #156
> Reshuffle the data and show first event

- windows/cavendish_particle_tracks.bat
Added `.bat` file to start `napari` with the plugin enabled.
> Add launcher to startup in Windows on lab machines

- src/cavendish_particle_tracks/_decay_angles_dialog.py
- src/cavendish_particle_tracks/_magnification_dialog.py
- src/cavendish_particle_tracks/_main_widget.py
- src/cavendish_particle_tracks/_stereoshift_dialog.py
- tests/test_decay_angles_dialog.py
- tests/test_magnification_dialog.py
- tests/test_stereoshift_dialog.py
Duplicate the layer management and behaviour from the `Magnification` tool to the `Stereoshift` and `DecayAngles` tools:
- The layers are hidden when the dialog is closed
- The dialog is persisted between invocations after the first one.
> Make all tools reusable

- src/cavendish_particle_tracks/_main_widget.py
We know and understand these warnings, and will deal with them or work around if/when we need to update to `napari` 0.6. So let's suppress them explicitly.
At the moment our `napari` dependency is pinned to a maximum version.
> Suppress the `FutureWarning`s from `napari`.

- src/cavendish_particle_tracks/_main_widget.py
Seems to solve 
- #119.
Probably it's anyway better to let Qt/`napari` handle where things appear on screen. This should not be the business of a plugin.
> Don't move dialogs when opening them.

- launch_debug.py
- src/cavendish_particle_tracks/_main_widget.py
- tests/test_widget.py
As argued for in the body of 
- #170 
I think this makes things nicer and more usable. Sorry for being boring!
In right-docked:
In bottom-docked:
> Remove ascii art.
